### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by fabaff** [sander76/aio-powerview-api#17]
With `aiohttpp-3.8.0` one test seems to fail.

```bash
============================= test session starts ==============================
platform linux -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /build/aiopvapi-1.6.14
============================= test session starts ==============================
platform linux -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /build/source
collected 53 items                                                             

collected 22 items                                                             

tests/test_environ.py F........                                          [ 40%]
tests/test_errors.py .                                                   [ 45%]
tests/test_inbuf_overflow.py ..                                          [ 54%]
tests/test_max_request_body_size.py ..                                   [ 63%]
tests/test_start_response.py ...                                         [ 77%]
tests/test_static.py ....                                                [ 95%]
tests/test_wsgi.py .                                                     [100%]

=================================== FAILURES ===================================
___________________________ EnvironTest.testEnviron ____________________________

self = <tests.test_environ.EnvironTest testMethod=testEnviron>

    def testEnviron(self) -> None:
        with self.run_server(assert_environ) as client:
>           client.assert_response(headers={
                "Foo": "bar",
            })

tests/test_environ.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/base.py:43: in assert_response
    self._test_case.assertEqual(response.status, 200)
E   AssertionError: 500 != 200
------------------------------ Captured log call -------------------------------
ERROR    aiohttp.server:web_protocol.py:400 Error handling request
Traceback (most recent call last):
  File "/nix/store/my82x39dchn0jp810nliflnrf6bvld4b-python3.9-aiohttp-3.8.0/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 430, in _handle_request
    resp = await request_handler(request)
  File "/nix/store/my82x39dchn0jp810nliflnrf6bvld4b-python3.9-aiohttp-3.8.0/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/build/source/aiohttp_wsgi/wsgi.py", line 294, in handle_request
    return await self._loop.run_in_executor(
  File "/nix/store/5bh6rpya1ar6l49vrhx1rg58dsa42906-python3-3.9.6/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/build/source/aiohttp_wsgi/wsgi.py", line 147, in _run_application
    body_iterable = application(environ, start_response)
  File "/build/source/tests/test_environ.py", line 13, in do_environ_application
    func(environ)
  File "/build/source/tests/test_environ.py", line 23, in assert_environ
    assert environ["CONTENT_TYPE"] == ""
AssertionError: assert 'application/octet-stream' == ''
  + application/octet-stream
=========================== short test summary info ============================
FAILED tests/test_environ.py::EnvironTest::testEnviron - AssertionError: 500 ...
========================= 1 failed, 21 passed in 0.36s =========================
````

**Comment by fabaff** [comment]
Looks like that https://github.com/sander76/aio-powerview-api/pull/13 helps if applied.

**Comment by sander76** [comment]
new release : https://pypi.org/project/aiopvapi/
v1.6.19
