### ISSUE TITLE
Tilt broken for shutters

### ISSUE THREAD

**Issue by robert-alfaro** [sander76/aio-powerview-api#34]
I have Palm Beach shutters and the tilt control does not work, throws exception (viewed from HA): 
```
2024-01-24 17:07:57.188 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [127641256996928] ShadeTiltOnly.move() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/workspaces/home-assistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/home-assistant/homeassistant/core.py", line 2230, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/workspaces/home-assistant/homeassistant/core.py", line 2267, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/home-assistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/home-assistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/workspaces/home-assistant/homeassistant/components/hunterdouglas_powerview/cover.py", line 415, in async_set_cover_tilt_position
    await self._async_set_cover_tilt_position(kwargs[ATTR_TILT_POSITION])
  File "/workspaces/home-assistant/homeassistant/components/hunterdouglas_powerview/cover.py", line 425, in _async_set_cover_tilt_position
    await self._async_execute_move(self._get_shade_tilt(target_hass_tilt_position))
  File "/workspaces/home-assistant/homeassistant/components/hunterdouglas_powerview/cover.py", line 233, in _async_execute_move
    response = await self._shade.move(move.request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ShadeTiltOnly.move() takes 1 positional argument but 2 were given
```

Discovered that the `move()` method is not actually implemented. I commented out the override just to see what happens.
Turns out the shutters tilt functions correctly without the override in place, however state reporting and such appears broken.
```
class ShadeTiltOnly(BaseShadeTilt):
    """Type 5 - Tilt Only 180°

    A shade with tilt anywhere capabilities only.
    """

    shade_types = (
        shade_type(66, "Palm Beach Shutters"),
    )

    capability = capability(
        5,
        ShadeCapabilities(
            tiltAnywhere=True,
            tilt180=True,
        ),
        "Tilt Only 180°",
    )

    open_position = {}
    close_position = {}

    open_position_tilt = {ATTR_POSITION1: MID_POSITION, ATTR_POSKIND1: 3}
    close_position_tilt = {ATTR_POSITION1: MIN_POSITION, ATTR_POSKIND1: 3}

    allowed_positions = (
        {ATTR_POSITION: {ATTR_POSKIND1: 3}, ATTR_COMMAND: ATTR_TILT},
    )

    # async def move(self):
    #     _LOGGER.error("Move not supported.")
    #     return
```

What can I do to provide more information or help out? I do recall manually trying "the other" python lib for powerview and it works for controlling tilt fine (it's been done before in python) but clearly bailed on it as this one is used in the HA integration.

Thank you for all your great work!

**Comment by kingy444** [comment]
I think I fixed this in 3.0.2 - but that won't be available in HA until the integration for Gen 3 gets pushed through. There was a rewrite from v2 to v3 so that both gen2 and gen3 hubs would work

Annoyingly, a change that a different HA PR made (and I needed to merge) meant that some tests need to be written before they will merge it

I simply haven't had time to figure that one out

I believe there was an issue raised on the HA git for a similar issue but it has auto closed now.
I'll leave this open until Gen 3 is pushed out

**Comment by robert-alfaro** [comment]
Thanks for the information. I stupidly assumed HA was pointed at latest release, not 2.0.4! If I can help rewrite something, I'm all for it.

**Comment by kingy444** [comment]
Please report back once the HA side is public so we can close this one off

Should be a few weeks away

**Comment by robert-alfaro** [comment]
updated today and there's a more catastrophic bug that occurred in the HA cover layer:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 865, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1328, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 318, in state
    if (closed := self.is_closed) is None:
                  ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hunterdouglas_powerview/cover.py", line 150, in is_closed
    return self.positions.primary <= CLOSED_POSITION
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

**Comment by kingy444** [comment]
I'm away for the next week but should be easy once I'm back - thought I had covered these but clearly missed a scenario 

In HA - can you click "Visit" on one of the palm beach and share the json here please

**Comment by robert-alfaro** [comment]
```json
{"shade":{"id":32094,"type":66,"capabilities":5,"batteryKind":2,"smartPowerSupply":{"status":0,"id":0,"port":0},"batteryStatus":3,"batteryStrength":110,"roomId":44034,"firmware":{"revision":2,"subRevision":0,"build":2180,"index":50},"name":"RGluaW5nIFJvb20gV2luZG93","groupId":33132,"signalStrength":4,"positions":{"posKind1":3,"position1":65535}}}
```

**Comment by robert-alfaro** [comment]
Latest release ha 2024.4 is working, thanks!
